### PR TITLE
Port to GTK 3, Port to Python 3

### PR DESCRIPTION
**Pull request by pidddgy**
rendering is weird for some reason:

image

### CODE REVIEW

**Comment by pidddgy** [comment]
interesting, i tried setting it to just a blue rectangle and that seems to work fine?

```python
def svg_str_to_pixbuf(svg_string):
    """ Load pixbuf from SVG string """
    svg_string = """
 <svg width="350" height="110">
   <rect width="300" height="100" style="fill:rgb(0,0,255);stroke-width:3;stroke:rgb(0,0,0)" />
   </svg> 
"""
    pl = GdkPixbuf.PixbufLoader.new_with_type('svg')
    pl.write(svg_string.encode('utf-8', 'ignore'))
    pl.close()
    pixbuf = pl.get_pixbuf()
    return pixbuf
```

image

**Comment by srevinsaju** [comment]
image

**Comment by quozl** [comment]
`Slide.__init__` has a few of your debug prints left behind.

**Comment by pidddgy** [comment]
my bad, fixed!

**Comment by quozl** [comment]
Thanks.  Reviewed.  Tested.

**Pull request merged**
