### PR TITLE
Port to Python3

### PR DESCRIPTION
**Pull request by pratyush3124**
Port to Python3.
Please find any flaws if there are.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Briefly reviewed.  Some of your changes don't pass flake8.  Please fix those, but not other flake8 errors.  Briefly tested.  Errors that occur suggest you cannot have tested this in any current release of Sugar.  Please test before commit.

**Comment by pratyush3124** [comment]
Ok

**Comment by pidddgy** [comment]
resolved in #3

**Comment by quozl** [comment]
Closing, stale, replaced by later pull request.

**Pull request closed without merging**
